### ISSUE TITLE
New language to work on

### ISSUE THREAD

**Issue by binary141** [kcpetersen111/learnLanguages#1]
I would like to see you implement FORTRAN or the folders programming language so I can see a basic idea on how to start these projects

**Comment by kcpetersen111** [comment]
What would you like to see done with these languages? Area there projects you would like to see done with these?

**Comment by kcpetersen111** [comment]
@Binary141  What would you like to see done with these languages? Area there projects you would like to see done with these?

**Comment by binary141** [comment]
So I have read that FORTRAN is good for data modeling, so I would like to see a program like that with some very simple predictions based on a given data set. 
For the folders language, it would be neat to see an implementation of getting user input and output to see what that is like and how time consuming it would be to create

**Comment by kcpetersen111** [comment]
The folders language will be too unwieldy to use on github but I will get on the basics of Fortran.

**Comment by binary141** [comment]
Is there any update on this addition @kcpetersen111 ?
