### ISSUE TITLE
Using another language in you perl folder

### ISSUE THREAD

**Issue by binary141** [kcpetersen111/learnLanguages#10]
Yes, hello. I am letting you know that your perl project also has some .go files that do not need to be there in the perl directory. I would like to see you implement that code using perl

**Comment by kcpetersen111** [comment]
This is because go is such a great language it is unimportant that it is used in a perl program.  Go is called the c of the 21st century and is the future of low level systems programming. If you could kindly refrain from being uninformed I would greatly apricate it.

**Comment by binary141** [comment]
Yes hi, please do not disrespect my mother in this fashion. You have disgraced my family and me with this comment. I am a very knowledgeable dev in this subject, and you have no reason to use such a new language with an ancient language. I would still like to see you implement the go part in perl
